# Generated by Django 4.1 on 2022-08-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=10, null=True)),
                ('attached', models.FileField(upload_to='uploads/', verbose_name='첨부파일')),
            ],
        ),
    ]
