# Generated by Django 3.2.18 on 2023-04-24 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_stats',
            name='f_id',
            field=models.ForeignKey(db_column='f_id', on_delete=django.db.models.deletion.CASCADE, to='analysis.fileupload'),
        ),
    ]
