# Generated by Django 4.1 on 2023-03-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_basic_stats_remove_fileupload_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic_stats',
            name='name',
        ),
        migrations.AlterField(
            model_name='basic_stats',
            name='count',
            field=models.TextField(),
        ),
    ]
