# Generated by Django 4.1 on 2023-04-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_basic_stats_f_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanced_analyis',
            name='test',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='basic_stats',
            name='active_time',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='basic_stats',
            name='user_count',
            field=models.TextField(default=''),
        ),
    ]
