# Generated by Django 4.1 on 2023-03-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_remove_basic_stats_name_alter_basic_stats_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_stats',
            name='active_time',
            field=models.IntegerField(default=3),
        ),
    ]
