# Generated by Django 4.1 on 2023-03-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_basic_stats_active_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basic_stats',
            old_name='count',
            new_name='user_count',
        ),
        migrations.AddField(
            model_name='basic_stats',
            name='user_words_count',
            field=models.TextField(null=True),
        ),
    ]
