# Generated by Django 4.1 on 2023-04-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_rename_count_basic_stats_user_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advanced_analyis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.TextField()),
            ],
        ),
    ]
